export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';


export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';


export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATION = 'GET_LOCATION';
export const SAVE_LOCATIONS = 'SAVE_LOCATIONS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SORT_LOCATIONS = 'SORT_LOCATIONS';
export const GROUP_LOCATIONS = 'GROUP_LOCATIONS';


